# Generated by Django 3.1.4 on 2023-12-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.IntegerField()),
                ('applicant', models.CharField(max_length=100)),
                ('facilityType', models.CharField(max_length=100)),
                ('cnn', models.IntegerField()),
                ('locationDescription', models.CharField(max_length=2100)),
                ('address', models.CharField(max_length=100)),
                ('blocklot', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('permit', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('foodItems', models.CharField(max_length=2100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('schedule', models.CharField(max_length=250)),
                ('dayshours', models.CharField(max_length=100)),
                ('approved', models.CharField(max_length=100)),
                ('received', models.IntegerField()),
                ('priorPermit', models.BooleanField()),
                ('expirationDate', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('firePreventionDistricts', models.IntegerField()),
                ('policeDistricts', models.IntegerField()),
                ('supervisorDistricts', models.IntegerField()),
                ('zipCodes', models.IntegerField()),
                ('neighborhoods', models.IntegerField()),
            ],
        ),
    ]
